apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - name: redis-server
      protocol: TCP
      port: 6379
      targetPort: 6379
    - name: redis-insights
      protocol: TCP
      port: 8001
      targetPort: 8001
  type: LoadBalancer