# fastapi-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 1 # Number of replicas/pods you want to run
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-container
        image: sidpalas/k8s-getting-started:0.0.1
        ports:
        - containerPort: 80 # Port your FastAPI application is listening on
